In [3]:
import pandas as pd

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
import joblib

In [7]:
df = pd.read_csv("data/processed/clean_news.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/clean_news.csv'

In [ ]:
print(df["label"].value_counts())

label
1    22900
0    22857
Name: count, dtype: int64


In [ ]:
print(df[["text", "label"]].head())

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0


In [ ]:
df.head()

,text,label,clean_text
0,Gere faults Trump for blurring meaning of 'ref...,1,gere fault trump blurring meaning refugee terr...
1,German parties start to find common ground in ...,1,german party start find common ground coalitio...
2,Senate Democratic leader says Attorney General...,1,senate democratic leader say attorney general ...
3,"Tennis: Kyrgios fined $10,000 for Shanghai wal...",1,tennis kyrgios fined shanghai walk tennis chin...
4,Trump Threw Mar-A-Lago Fundraiser For Woman A...,0,trump threw maralago fundraiser woman center b...


In [ ]:
df.columns

Index(['text', 'label', 'clean_text'], dtype='str')

In [ ]:
df.columns

Index(['text', 'label', 'clean_text'], dtype='str')

In [ ]:
X = df["clean_text"]

y = df["label"]

In [ ]:
print(X.head())

print()

print(y.head())

0    gere fault trump blurring meaning refugee terr...
1    german party start find common ground coalitio...
2    senate democratic leader say attorney general ...
3    tennis kyrgios fined shanghai walk tennis chin...
4    trump threw maralago fundraiser woman center b...
Name: clean_text, dtype: str

0    1
1    1
2    1
3    1
4    0
Name: label, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
print("Training samples :", len(X_train))
print("Testing samples  :", len(X_test))

Training samples : 36605
Testing samples  : 9152


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    min_df=5,
    max_df=0.8
)

In [ ]:
df["clean_text"].isna().sum()

np.int64(5)

In [ ]:
df["clean_text"] = df["clean_text"].fillna("")

In [ ]:
print(df["clean_text"].isna().sum())

0


In [ ]:
print(df["clean_text"].dtype)

str


In [ ]:
print(df["clean_text"].head())

0    gere fault trump blurring meaning refugee terr...
1    german party start find common ground coalitio...
2    senate democratic leader say attorney general ...
3    tennis kyrgios fined shanghai walk tennis chin...
4    trump threw maralago fundraiser woman center b...
Name: clean_text, dtype: str


In [ ]:
X = df["clean_text"]
y = df["label"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [ ]:
print("Training Shape :", X_train_tfidf.shape)
print("Testing Shape  :", X_test_tfidf.shape)

Training Shape : (36605, 5000)
Testing Shape  : (9152, 5000)


In [ ]:
print("Vocabulary Size:", len(tfidf.vocabulary_))

Vocabulary Size: 5000


In [ ]:
feature_names = tfidf.get_feature_names_out()

print(feature_names[:20])

['abandon' 'abandoned' 'abc' 'abc news' 'abe' 'abedin' 'ability' 'able'
 'abortion' 'abroad' 'absence' 'absolute' 'absolutely' 'abu' 'abuse'
 'academic' 'academy' 'accept' 'acceptable' 'accepted']


In [ ]:
import joblib

joblib.dump(tfidf, "models/tfidf_vectorizer.pkl")

['models/tfidf_vectorizer.pkl']

In [ ]:
print(type(X_train_tfidf))
print(type(y_train))

<class 'scipy.sparse._csr.csr_matrix'>
<class 'pandas.Series'>


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [ ]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

In [ ]:
logistic_prediction = logistic_model.predict(X_test_tfidf)

In [ ]:
print("Logistic Regression Accuracy:",
      accuracy_score(y_test, logistic_prediction))

Logistic Regression Accuracy: 0.9750874125874126


In [ ]:
print(classification_report(y_test, logistic_prediction))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98      4572
           1       0.98      0.97      0.98      4580

    accuracy                           0.98      9152
   macro avg       0.98      0.98      0.98      9152
weighted avg       0.98      0.98      0.98      9152



In [ ]:
print(confusion_matrix(y_test, logistic_prediction))

[[4459  113]
 [ 115 4465]]


In [ ]:
naive_model = MultinomialNB()

naive_model.fit(X_train_tfidf, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](2,)","[18285.,18320.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](2,)","[-0.69,-0.69]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](2, 5000)","[[ 7.58, 8.68,47.42,..., 2.04,27.96, 0. ], [12.43,10.26,17.81,...,45.25,43.97,31.26]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](2, 5000)","[[ -9.86, -9.74, -8.13,...,-10.9 , -8.65,-12.01], [ -9.42, -9.6 , -9.08,..., -8.18, -8.21, -8.55]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,5000


In [ ]:
naive_prediction = naive_model.predict(X_test_tfidf)

In [ ]:
print("Naive Bayes Accuracy:",
      accuracy_score(y_test, naive_prediction))

Naive Bayes Accuracy: 0.9242788461538461


In [ ]:
print(classification_report(y_test, naive_prediction))

              precision    recall  f1-score   support

           0       0.92      0.93      0.92      4572
           1       0.93      0.92      0.92      4580

    accuracy                           0.92      9152
   macro avg       0.92      0.92      0.92      9152
weighted avg       0.92      0.92      0.92      9152



In [ ]:
print(confusion_matrix(y_test, naive_prediction))

[[4240  332]
 [ 361 4219]]


In [ ]:
svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

svm_prediction = svm_model.predict(X_test_tfidf)

print("Linear SVM Accuracy:",
      accuracy_score(y_test, svm_prediction))

print(classification_report(y_test, svm_prediction))

print(confusion_matrix(y_test, svm_prediction))

Linear SVM Accuracy: 0.9831730769230769
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      4572
           1       0.99      0.98      0.98      4580

    accuracy                           0.98      9152
   macro avg       0.98      0.98      0.98      9152
weighted avg       0.98      0.98      0.98      9152

[[4505   67]
 [  87 4493]]


In [ ]:
forest = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

forest.fit(X_train_tfidf, y_train)

forest_prediction = forest.predict(X_test_tfidf)

print("Random Forest Accuracy:",
      accuracy_score(y_test, forest_prediction))

print(classification_report(y_test, forest_prediction))

print(confusion_matrix(y_test, forest_prediction))

Random Forest Accuracy: 0.9796765734265734
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      4572
           1       0.99      0.97      0.98      4580

    accuracy                           0.98      9152
   macro avg       0.98      0.98      0.98      9152
weighted avg       0.98      0.98      0.98      9152

[[4532   40]
 [ 146 4434]]


In [ ]:
import joblib

joblib.dump(X_train_tfidf, "models/X_train_tfidf.pkl")
joblib.dump(X_test_tfidf, "models/X_test_tfidf.pkl")

joblib.dump(y_train, "models/y_train.pkl")
joblib.dump(y_test, "models/y_test.pkl")

['models/y_test.pkl']

# Bag of Words (BoW)

Bag of Words converts text into numerical vectors based on the frequency of each word in the dataset. Unlike TF-IDF, it only counts word occurrences and does not reduce the importance of frequently occurring words.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [1]:
%whos

Interactive namespace is empty.


In [5]:
import pandas as pd

df = pd.read_csv("../data/processed/clean_news.csv")
df.head()

,text,label,clean_text
0,Gere faults Trump for blurring meaning of 'ref...,1,gere fault trump blurring meaning refugee terr...
1,German parties start to find common ground in ...,1,german party start find common ground coalitio...
2,Senate Democratic leader says Attorney General...,1,senate democratic leader say attorney general ...
3,"Tennis: Kyrgios fined $10,000 for Shanghai wal...",1,tennis kyrgios fined shanghai walk tennis chin...
4,Trump Threw Mar-A-Lago Fundraiser For Woman A...,0,trump threw maralago fundraiser woman center b...


In [6]:
import os

print(os.path.exists("../data/processed/clean_news.csv"))
print(os.path.exists("../data/raw/news.csv"))

True
True


In [8]:
df.columns

Index(['text', 'label', 'clean_text'], dtype='str')

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
df["clean_text"].isnull().sum()

np.int64(5)

In [12]:
df = df.dropna(subset=["clean_text"])

In [13]:
df = df[df["clean_text"].notna()]

In [14]:
df["clean_text"].isnull().sum()

np.int64(0)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(max_features=5000)

X_bow = bow.fit_transform(df["clean_text"])

print(X_bow.shape)

(45752, 5000)


In [16]:
df[["clean_text"]].head()

,clean_text
0,gere fault trump blurring meaning refugee terr...
1,german party start find common ground coalitio...
2,senate democratic leader say attorney general ...
3,tennis kyrgios fined shanghai walk tennis chin...
4,trump threw maralago fundraiser woman center b...


In [18]:
sample_df = pd.DataFrame(
    X_bow[:5, :20].toarray(),
    columns=bow.get_feature_names_out()[:20]
)

sample_df

,aaron,abandon,abandoned,abbas,abc,abdullah,abe,abedin,ability,able,abortion,abroad,absence,absolute,absolutely,absurd,abu,abuse,abused,academic
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


In [19]:
print("Bag of Words Matrix Shape:", X_bow.shape)

Bag of Words Matrix Shape: (45752, 5000)


In [20]:
print("Vocabulary Size:", len(bow.get_feature_names_out()))

Vocabulary Size: 5000


In [21]:
print(bow.get_feature_names_out()[:20])

['aaron' 'abandon' 'abandoned' 'abbas' 'abc' 'abdullah' 'abe' 'abedin'
 'ability' 'able' 'abortion' 'abroad' 'absence' 'absolute' 'absolutely'
 'absurd' 'abu' 'abuse' 'abused' 'academic']
